/* Normally generated by libjxl's build. The door only needs the declarations: it loads libjxl at run time. */
#ifndef JXL_EXPORT_H
#define JXL_EXPORT_H
#define JXL_EXPORT
#define JXL_DEPRECATED
#endif
