/* Normally generated by libjxl's build: these are the headers of libjxl 0.11.1. */
#ifndef JXL_VERSION_H_
#define JXL_VERSION_H_
#define JPEGXL_MAJOR_VERSION 0
#define JPEGXL_MINOR_VERSION 11
#define JPEGXL_PATCH_VERSION 1
#define JPEGXL_NUMERIC_VERSION ((0 << 24) | (11 << 16) | (1 << 8))
#define JPEGXL_COMPUTE_NUMERIC_VERSION(major, minor, patch) (((major) << 24) | ((minor) << 16) | ((patch) << 8))
#endif
